import katalon from "@katalon-studio/cloud-test";

export default katalon.testCase("New Test Case", async ({ local, web }) => {
  await new Promise((r) => setTimeout(r, 0));
  await web.openBrowser("https://katalon-demo-cura.herokuapp.com");
  await web.click({
    type: "Web",
    id: "16abf27b-4754-4d9b-91b4-82b27e0b94f3",
    attributes: {
      id: "menu-toggle",
      href: "#",
      class: "btn btn-dark btn-lg toggle",
    },
    childIndex: 1,
    hashes: { "md5.v1": "bd1a4d233fee02bdbcf85af89867c9de" },
    name: "a - btn btn-dark btn-lg toggle",
    selectors: [
      {
        id: "5e423041-73d3-428d-bd80-5e9f704daec0",
        type: "CSS",
        value: "#menu-toggle",
        isDefault: true,
      },
      {
        id: "f27c959f-ac18-4564-91f7-b38bb844feba",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "a74e835f-570e-487e-bbf2-cb51dbe9213f",
    attributes: {
      href: "profile.php#login",
      onclick: "$('#menu-close').click();",
    },
    childIndex: 1,
    hashes: { "md5.v1": "0bd0cc05e00accd5b4b22670791231d9" },
    name: "a - Login",
    selectors: [
      {
        id: "ed3be2cc-06b3-4085-bf31-72e956977162",
        type: "CSS",
        value: '[href="profile\\.php\\#login"]',
        isDefault: true,
      },
      {
        id: "31508d36-c624-46aa-9cc0-1235bc7235ff",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "Login",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "6231311d-2d28-493b-90ad-506e9b435558",
    attributes: {
      type: "text",
      class: "form-control",
      placeholder: "Username",
      "aria-describedby": "demo_username_label",
      value: "John Doe",
      readonly: "",
    },
    childIndex: 2,
    hashes: { "md5.v1": "c3b978327df97741bf8f19a0016fb018" },
    name: "input - Username",
    selectors: [
      {
        id: "d8d49cb6-edab-4c5c-bf0c-06dd2bd97c12",
        type: "CSS",
        value: '[aria-describedby="demo_username_label"]',
        isDefault: true,
      },
      {
        id: "eebacb46-eae7-42ad-9d8a-857004209e79",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "960d6d59-d67d-4b9b-a7fb-3a5837d88a36",
    attributes: {
      type: "text",
      class: "form-control",
      id: "txt-username",
      name: "username",
      placeholder: "Username",
      value: "",
      autocomplete: "off",
    },
    childIndex: 1,
    hashes: { "md5.v1": "57f176ba19cb19cc93acaba2dbde6b10" },
    name: "input - Username",
    selectors: [
      {
        id: "7d44d641-9aec-4ccf-9359-091ba5b9101c",
        type: "CSS",
        value: "#txt-username",
        isDefault: true,
      },
      {
        id: "2af9b93f-23e5-4650-9cc7-9e8de6784843",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.setText(
    {
      type: "Web",
      id: "960d6d59-d67d-4b9b-a7fb-3a5837d88a36",
      attributes: {
        type: "text",
        class: "form-control",
        id: "txt-username",
        name: "username",
        placeholder: "Username",
        value: "",
        autocomplete: "off",
      },
      childIndex: 1,
      hashes: { "md5.v1": "57f176ba19cb19cc93acaba2dbde6b10" },
      name: "input - Username",
      selectors: [
        {
          id: "7d44d641-9aec-4ccf-9359-091ba5b9101c",
          type: "CSS",
          value: "#txt-username",
          isDefault: true,
        },
        {
          id: "2af9b93f-23e5-4650-9cc7-9e8de6784843",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "input",
      text: "",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
      parentIframe: null,
      shadowRoot: null,
    },
    "John Doe"
  );
  await web.click({
    type: "Web",
    id: "974683eb-b678-4cf7-8d7e-2e9ac48bc1ed",
    attributes: {
      type: "text",
      class: "form-control",
      placeholder: "Password",
      "aria-describedby": "demo_password_label",
      value: "ThisIsNotAPassword",
      readonly: "",
    },
    childIndex: 2,
    hashes: { "md5.v1": "24a673adca17019b53bb33cc2dceb62f" },
    name: "input - Password",
    selectors: [
      {
        id: "986bdea4-0eba-44c4-acca-b6895593eb34",
        type: "CSS",
        value: '[aria-describedby="demo_password_label"]',
        isDefault: true,
      },
      {
        id: "9da81d91-c27a-460c-af31-27fbf7e3dd1b",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "3f16b521-5d66-4927-9a57-69bb57c1c08b",
    attributes: {
      type: "password",
      class: "form-control",
      id: "txt-password",
      name: "password",
      placeholder: "Password",
      value: "",
      autocomplete: "off",
    },
    childIndex: 1,
    hashes: { "md5.v1": "fe634c654141065106a978262a410740" },
    name: "input - Password",
    selectors: [
      {
        id: "c5bba3d2-c19b-420c-9b34-825d3a1d647d",
        type: "CSS",
        value: "#txt-password",
        isDefault: true,
      },
      {
        id: "0fe03bae-9f7a-42ff-a7e6-58973d338a4b",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.setEncryptedText(
    {
      type: "Web",
      id: "3f16b521-5d66-4927-9a57-69bb57c1c08b",
      attributes: {
        type: "password",
        class: "form-control",
        id: "txt-password",
        name: "password",
        placeholder: "Password",
        value: "",
        autocomplete: "off",
      },
      childIndex: 1,
      hashes: { "md5.v1": "fe634c654141065106a978262a410740" },
      name: "input - Password",
      selectors: [
        {
          id: "c5bba3d2-c19b-420c-9b34-825d3a1d647d",
          type: "CSS",
          value: "#txt-password",
          isDefault: true,
        },
        {
          id: "0fe03bae-9f7a-42ff-a7e6-58973d338a4b",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "input",
      text: "",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
      parentIframe: null,
      shadowRoot: null,
    },
    "144750d5c1eeeed0d2d2abaa74e060aa-U2FsdGVkX1+d2ofe5OvYs2xFPSeDu5AdoOu+RQh50ssTa9IRVbYwatP0i6z5zN/e"
  );
  await web.click({
    type: "Web",
    id: "d12cc5f7-2316-4e0e-87e5-8672bb9ba147",
    attributes: { id: "btn-login", type: "submit", class: "btn btn-default" },
    childIndex: 1,
    hashes: { "md5.v1": "50aa64147a00037c420def1e18673ac9" },
    name: "button - Login",
    selectors: [
      {
        id: "694b81ca-eb59-4d28-a32e-f59226c7bc6d",
        type: "CSS",
        value: "#btn-login",
        isDefault: true,
      },
      {
        id: "97b0319d-8641-4cef-a46d-70b455a10f38",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "button",
    text: "Login",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "b48e3bf7-dcbf-4aff-b327-d35a9aa51f63",
    attributes: {
      id: "combo_facility",
      name: "facility",
      class: "form-control",
    },
    childIndex: 1,
    hashes: { "md5.v1": "eb61194c54579bb83036a03574c5c597" },
    name: "select - Tokyo CURA Healthcare Center",
    selectors: [
      {
        id: "74cc35bc-4591-4890-9039-3a9c4c625b77",
        type: "CSS",
        value: "#combo_facility",
        isDefault: true,
      },
      {
        id: "39f48ce4-9097-44f2-bbb2-a9200bafd05a",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "select",
    text: "Tokyo CURA Healthcare Center\nHongkong CURA Healthcare Center\nSeoul CURA Healthcare Center",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.selectOptionByValue(
    {
      type: "Web",
      id: "b48e3bf7-dcbf-4aff-b327-d35a9aa51f63",
      attributes: {
        id: "combo_facility",
        name: "facility",
        class: "form-control",
      },
      childIndex: 1,
      hashes: { "md5.v1": "eb61194c54579bb83036a03574c5c597" },
      name: "select - Tokyo CURA Healthcare Center",
      selectors: [
        {
          id: "74cc35bc-4591-4890-9039-3a9c4c625b77",
          type: "CSS",
          value: "#combo_facility",
          isDefault: true,
        },
        {
          id: "39f48ce4-9097-44f2-bbb2-a9200bafd05a",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "select",
      text: "Tokyo CURA Healthcare Center\nHongkong CURA Healthcare Center\nSeoul CURA Healthcare Center",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
      parentIframe: null,
      shadowRoot: null,
    },
    "Hongkong CURA Healthcare Center"
  );
  await web.click({
    type: "Web",
    id: "cbcd0748-14cc-46db-a5aa-73bfbbfad4e5",
    attributes: { for: "chk_hospotal_readmission", class: "checkbox-inline" },
    childIndex: 1,
    hashes: { "md5.v1": "6d44f92a2dd56a668058ec302ef5287e" },
    name: "label - Apply for hospital readmission",
    selectors: [
      {
        id: "0f6f368f-367a-4962-817b-cf437def3523",
        type: "CSS",
        value: ".checkbox-inline",
        isDefault: true,
      },
      {
        id: "129e5fdf-c02f-4197-9381-1e736711e96b",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "label",
    text: "Apply for hospital readmission",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "5b6ee5eb-1f2c-4564-bc99-853f9fd1124d",
    attributes: { class: "radio-inline" },
    childIndex: 2,
    hashes: { "md5.v1": "0327f13f35dc137bce039c73c4d1a0b4" },
    name: "label - Medicaid",
    selectors: [
      {
        id: "fd15eb67-6264-452c-951f-e50e40565e8f",
        type: "CSS",
        value: ".radio-inline:nth-child(2)",
        isDefault: true,
      },
      {
        id: "a972e683-08a1-4a38-8a40-60f49e844c86",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "label",
    text: "Medicaid",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "9f827c11-47c6-425e-b202-a0bc9a5362be",
    attributes: {
      type: "text",
      class: "form-control",
      id: "txt_visit_date",
      name: "visit_date",
      placeholder: "dd/mm/yyyy",
      autocomplete: "off",
      required: "",
    },
    childIndex: 1,
    hashes: { "md5.v1": "055cc9a2ee5ca19d0a879ebe370aa30e" },
    name: "input - dd/mm/yyyy",
    selectors: [
      {
        id: "b68e6e43-70d7-4b3f-bbce-e25035190464",
        type: "CSS",
        value: "#txt_visit_date",
        isDefault: true,
      },
      {
        id: "ea379514-e036-4b27-8a48-565617172dc5",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "318ad9b1-e40d-478a-8d00-9947402a408a",
    attributes: { class: "day" },
    childIndex: 3,
    hashes: { "md5.v1": "e6c889cc9407a87c81fe2e92a7aff365" },
    name: "td - 31",
    selectors: [
      {
        id: "26fe80fa-d5ac-4190-91c9-ab8594c99004",
        type: "CSS",
        value: "tr:nth-child(6) .day:nth-child(3)",
        isDefault: true,
      },
      {
        id: "ad881682-aac9-409f-aba1-14d258078cfb",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "td",
    text: "31",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "7c535adc-6240-475c-ae68-0349cfe74dc1",
    attributes: {
      class: "form-control",
      id: "txt_comment",
      name: "comment",
      placeholder: "Comment",
      rows: "10",
    },
    childIndex: 1,
    hashes: { "md5.v1": "b06c3c43a662648630c6cc9a9b0663f1" },
    name: "textarea - Comment",
    selectors: [
      {
        id: "fdcd8202-a575-44b4-92ae-68437f148a7d",
        type: "CSS",
        value: "#txt_comment",
        isDefault: true,
      },
      {
        id: "ab8ce52a-5d0f-4f25-a539-d4637d7a7d18",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "textarea",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.setText(
    {
      type: "Web",
      id: "7c535adc-6240-475c-ae68-0349cfe74dc1",
      attributes: {
        class: "form-control",
        id: "txt_comment",
        name: "comment",
        placeholder: "Comment",
        rows: "10",
      },
      childIndex: 1,
      hashes: { "md5.v1": "b06c3c43a662648630c6cc9a9b0663f1" },
      name: "textarea - Comment",
      selectors: [
        {
          id: "fdcd8202-a575-44b4-92ae-68437f148a7d",
          type: "CSS",
          value: "#txt_comment",
          isDefault: true,
        },
        {
          id: "ab8ce52a-5d0f-4f25-a539-d4637d7a7d18",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "textarea",
      text: "",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
      parentIframe: null,
      shadowRoot: null,
    },
    "Testing"
  );
  await web.click({
    type: "Web",
    id: "e4222312-42ae-4e83-ada2-4a523cadaa04",
    attributes: {
      id: "btn-book-appointment",
      type: "submit",
      class: "btn btn-default",
    },
    childIndex: 1,
    hashes: { "md5.v1": "56ef00cb92ad0547b9464c968fd02681" },
    name: "button - Book Appointment",
    selectors: [
      {
        id: "8517f7ed-28d5-4db5-86a5-b38826f26c64",
        type: "CSS",
        value: "#btn-book-appointment",
        isDefault: true,
      },
      {
        id: "915f5bb3-b8f8-440f-813d-91ed4c480106",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "button",
    text: "Book Appointment",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "3293d111-cb85-4684-a890-a08059e991c0",
    attributes: {
      class: "btn btn-default",
      href: "https://katalon-demo-cura.herokuapp.com/",
    },
    childIndex: 1,
    hashes: { "md5.v1": "706652890bf1fc29e80d791a1c2f601a" },
    name: "a - Go to Homepage",
    selectors: [
      {
        id: "4df05d30-1395-4e7d-b838-22ac557ff20f",
        type: "CSS",
        value: ".btn.btn-default",
        isDefault: true,
      },
      {
        id: "71cfeb16-5804-49d4-b5ea-3b5b6f902234",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "Go to Homepage",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/appointment.php#summary",
    parentIframe: null,
    shadowRoot: null,
  });
});